spring:
  #main.allow-bean-definition-overriding: true
  profiles:
    active:
      - core
      - mybatisplus
      #- kafka
  datasource:
    druid:
      #driver-class-name: com.mysql.jdbc.Driver
      #url: jdbc:mysql://49.4.1.42:3306/pmis-dev?useUnicode=true&characterEncoding=utf8
      #username: pmis-dev
      #password: pmisDev1028
      url: jdbc:mysql://localhost:3306/pmis-dev?useUnicode=true&characterEncoding=utf8
      username: root
      password: 1qaz2wsx
      db-type: mysql
  webflux:
    date-format: yyyy-MM-dd HH:mm:ss
shiro:
  enabled: true
  sessionManager:
    cookie:
      secure: true
  rememberMeManager:
    cookie:
      secure: true
  interceptUrls:
    - pattern: /**/table/**
      access: anon
    - pattern: /webjars/**
      access: anon
    - pattern: /**
      access: authc

logging:
  level:
    errorLog: error
    web: info
    org.apache.shiro: debug
    com:
      womow:
        toc:
          whocare: debug
